"use strict";
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const api=require('..'),core=require('@aikdna/kdna-core');
const {readBrowser}=require('@aikdna/kdna-read/browser');
const {createTrustedReadControlProvider,createTrustedHostReadProvider}=require('@aikdna/kdna-read/embedding');
const artifactRoot=path.resolve(process.env.STUDIO_TEST_ARTIFACT_ROOT || path.join(__dirname,'.artifacts',String(process.pid)));fs.mkdirSync(artifactRoot,{recursive:true});
let serial=0;const clone=x=>JSON.parse(JSON.stringify(x));
const whitebox=require('../src/creation-engine/component-input'),{buildMaterialization}=require('../src/compile/component-materialization'),{encodeComponentRuntime}=require('../src/compile/component-encoding'),descriptor=require('@aikdna/kdna-core/components').getComponentSemanticsContract();
const methods={recognition:{method:{term:'recognition'},components:[{localKey:'feature',type:'taxonomy',method:{term:'recognition'},role:'识别特征',statement:'The judgment distinguishes classes by whether an observation is available.',content:{items:[{key:'available',title:'Observation available',meaning:'An observation is available for the judgment.'},{key:'missing',title:'Observation missing',meaning:'No observation is available.'}],broader:[]}},{localKey:'classes',type:'candidate-set',method:{term:'recognition'},role:'类别定义',statement:'Known means an observation is available; unknown means it is not.',content:{items:[{key:'known',title:'Known',meaning:'An observation is available.'},{key:'unknown',title:'Unknown',meaning:'No observation is available.'}]}},{localKey:'match',type:'discriminator-set',method:{term:'recognition'},role:'匹配办法',statement:'Presence of an observation maps to known; absence maps to unknown.',content:{candidateSetLocalKey:'classes',items:[{key:'presence',title:'Observation presence',prompt:'Is an observation available?',contrasts:[{candidateKey:'known',criterion:'An observation is available.'},{candidateKey:'unknown',criterion:'No observation is available.'}]}]}}]},causalAnalysis:{method:{term:'causal_analysis'},components:[{localKey:'phenomenon',type:'taxonomy',method:{term:'causal_analysis'},role:'待解释现象',statement:'An input observation disappeared between input and output.',content:{items:[{key:'disappearance',title:'Disappearance after transformation',meaning:'An input observation disappeared between input and output.'}],broader:[]}},{localKey:'relation',type:'taxonomy',method:{term:'causal_analysis'},role:'原因关系',statement:'Each candidate cause explains how the observation disappeared.',content:{items:[{key:'missing',title:'Absent before transformation',meaning:'The input was absent before any transformation.'},{key:'transform',title:'Lost within transformation',meaning:'The input existed before transformation but not after.'}],broader:[]}},{localKey:'causes',type:'candidate-set',method:{term:'causal_analysis'},role:'候选原因',statement:'The competing causes for the disappeared observation.',content:{items:[{key:'missing',title:'Input absent',meaning:'The expected input was not observed.'},{key:'transform',title:'Transformation failed',meaning:'An input observation existed but disappeared after transformation.'}]}},{localKey:'checks',type:'discriminator-set',method:{term:'causal_analysis'},role:'区分依据',statement:'The disappearing boundary discriminates between the candidate causes.',content:{candidateSetLocalKey:'causes',items:[{key:'boundary',title:'Locate the boundary',prompt:'At which boundary did the observation disappear?',contrasts:[{candidateKey:'missing',criterion:'Input was absent before transformation.'},{candidateKey:'transform',criterion:'Input existed before transformation but not after.'}]}]}}]}};
const feelingDefault={method:{term:'feeling'},components:[{localKey:'basis',type:'taxonomy',method:{term:'feeling'},role:'个人感受',statement:'The authored preference rests on an actual felt priority.',content:{items:[{key:'care',title:'Felt priority',meaning:'The authored statement rests on an actual felt priority.'}],broader:[]}}]};
function fixture({method,receive,kind='delegated_agent_editorial'}={}){
 const id=++serial;let turn=0,next='select';const channel='synthetic-provider:'+id;
 const options={agent:{name:'Synthetic lifecycle fixture',version:'1'},syntheticFixture:true,adoptionInput:{kind,channel,...(kind==='delegated_agent_editorial'?{authorization:{coordinate:'fixture:local-only',statement:'Authorized synthetic implementation testing, no real editorial adoption.'}}:{}),receive:receive|| (async review=>({id:'response:'+id+':'+(++turn),role:kind==='delegated_agent_editorial'?'agent':'human',channel,review_id:review.review_id,text:next}))},interpretReply:async text=>text==='select'?{kind:'select',choices:[{judgmentLocalKey:'signal',alternativeLocalKey:'preserve'}]}:{kind:text}};
 const s=api.createSession(options);s.agent.setBrief({title:'Synthetic signal fixture',scope:'Local test of authoring and saved readback.',highest_question:'Which choice preserves honest uncertainty?'});
 const m=s.agent.recordMaterial({kind:'text',title:'Private input',content:'PRIVATE_MATERIAL_NEVER_RUNTIME_'+id,coordinate:'private:fixture:'+id});
 const a={localKey:'preserve',title:'Preserve uncertainty é e\u0301 𝄞',subject:'A synthetic observation',scope:'Only missing observations',statement:'Retain unknown when evidence is absent.\nQuoted "unknown" is not false.',rationale:'Missing input cannot establish a negative finding.',materialRefs:[m.id],method:clone(method||feelingDefault)};
 const b={...clone(a),localKey:'infer',statement:'Treat an absent observation as a negative result.'};s.agent.propose({localKey:'signal',alternatives:[a,b]});
 return {id,s,a,b,m,options,setReply:x=>{next=x;},async select(){next='select';await s.receiveAdoptionReply();},async confirm(){s.agent.compilePreview();next='confirm';await s.receiveAdoptionReply();},async ready(){await this.select();await this.confirm();return s.exportAsset();}};
}
async function publicRead(bytes){const admission=core.admitBytes(bytes);assert.equal(admission.status,'accepted');const snapshot=admission.snapshot;const control=createTrustedReadControlProvider(()=>({admission_response_limit_bytes:262144}));const host=createTrustedHostReadProvider({observe:({request,snapshot})=>({host_id:'synthetic-local-host',host_epoch:'fixture-epoch',decision_id:'fixture-decision',request_id:request.request_id,snapshot_id:snapshot.snapshot_id,A:snapshot.digests.A.observed,C:snapshot.digests.C.observed,scope:snapshot.ir.nodes.map(n=>n.id),issued_at:1000,expires_at:10000,current_ms:1001,decision:'allow',policy_id:'synthetic-read-only'})});return readBrowser(snapshot,{request_id:'fixture-read',tuple:snapshot.tuple,budget_bytes:1048576,mode:'exact_selection',selection:{asset_id:snapshot.asset.asset_id,asset_version:snapshot.asset.asset_version,judgment_id:snapshot.ir.catalog[0].judgment_id},handle:null},control,host);}
for(const [shape,method] of Object.entries({ordinary:undefined,...methods}))test('current public create/save/Core/Read: '+shape,async()=>{
 const f=fixture({method}),out=await f.ready();assert.equal(out.verification.status,'pending_saved_readback');assert.equal(out.bytes.includes(Buffer.from(f.m.content)),false);assert.equal(out.bytes.includes(Buffer.from(f.m.coordinate)),false);
 const file=path.join(artifactRoot,shape+'.kdna');fs.writeFileSync(file,out.bytes,{flag:'wx'});const bytes=fs.readFileSync(file);const completed=f.s.completeSave(bytes);assert.equal(completed.status,'accepted_with_live_context');assert.equal(completed.identity,'not_verified');assert.throws(()=>f.s.completeSave(bytes),{code:'CREATION_SAVE_STATE_INVALID'});assert.throws(()=>f.s.exportAsset(),{code:'CREATION_FINAL_REQUIRED'});
 const evidence=api.verifyCreationEvidence(bytes,out.evidence,out.binding);assert.equal(evidence.status,'consistent',JSON.stringify(evidence));assert.equal(evidence.live_context,'unavailable');assert.equal(evidence.creation_accepted,'not_evaluated');const read=await publicRead(bytes);assert.equal(read.channel,'read_envelope');assert.equal(read.envelope.status,'ready');if(method){const components=read.envelope.content.closure.filter(n=>n.role==='method_component');assert.ok(components.length>0,'Exact selection retains method components');assert.equal(components.length,method.components.length);}fs.writeFileSync(path.join(artifactRoot,shape+'.json'),JSON.stringify({evidence:out.evidence,binding:out.binding,completed,verification:evidence,read},null,2),{flag:'wx'});
});
test('human claim remains unverified and gets current format',async()=>{const f=fixture({kind:'human_claim_unverified'}),out=await f.ready();assert.equal(f.s.completeSave(out.bytes).adoption_kind,'human_claim_unverified');assert.equal(api.verifyCreationEvidence(out.bytes,out.evidence,out.binding).identity,'not_verified');});
for(const mutation of [a=>{a.injected=true;},a=>{a.method=null;},a=>{a.method={method:{term:'feeling'},components:null};},a=>{a.method={method:{term:'feeling'},components:undefined};},a=>{a.method={method:{term:'feeling'},definition_digest:'forged'};},a=>{a.method={method:{term:'feeling'},components:[{localKey:'c',type:'candidate-set',method:{term:'feeling'},role:'个人感受',statement:'The authored preference rests on an actual felt priority.',content:{items:[]},profile_id:'forged'}]};},a=>{a.method={method:{term:'feeling'},components:[],bindings:[{componentLocalKey:'missing',role:'test',target_ref:'foreign'}]};}])test('closed typed authoring rejects malformed/extra input '+(++serial),()=>{const f=fixture();const a=clone(f.a);mutation(a);assert.throws(()=>f.s.agent.revise('signal',{baseRevision:1,alternatives:[a,f.b],explanation:'Test rejected mutation.'}));});
const vocabularyNegatives=[['an unsupported method term',a=>{a.method={method:{term:'direct-preference'},components:[{localKey:'b',type:'taxonomy',method:{term:'direct-preference'},role:'个人感受',statement:'The authored preference rests on an actual felt priority.',content:{items:[{key:'x',title:'X',meaning:'X.'}],broader:[]}}]};},'COMPONENT_METHOD_TERM_UNSUPPORTED'],['a role outside the method family',a=>{a.method={method:{term:'feeling'},components:[{localKey:'b',type:'taxonomy',method:{term:'feeling'},role:'input-items',statement:'Attempted non-family role.',content:{items:[{key:'x',title:'X',meaning:'X.'}],broader:[]}}]};},'COMPONENT_ROLE_UNKNOWN'],['a missing required role',a=>{a.method={method:{term:'recognition'},components:[{localKey:'b',type:'taxonomy',method:{term:'recognition'},role:'识别特征',statement:'The judgment distinguishes classes by whether an observation is available.',content:{items:[{key:'x',title:'X',meaning:'X.'}],broader:[]}}]};},'CREATION_METHOD_INCOMPLETE'],['a component method differing from the judgment term',a=>{a.method={method:{term:'feeling'},components:[{localKey:'b',type:'taxonomy',method:{term:'recognition'},role:'个人感受',statement:'The authored preference rests on an actual felt priority.',content:{items:[{key:'x',title:'X',meaning:'X.'}],broader:[]}}]};},'COMPONENT_METHOD_TERM_MISMATCH'],['an undeclared method',a=>{delete a.method;},'CREATION_METHOD_REQUIRED'],['an empty method (no components)',a=>{a.method={method:{term:'feeling'},components:[]};},'CREATION_METHOD_INCOMPLETE'],['an empty required-role content',a=>{a.method={method:{term:'recognition'},components:[{localKey:'feature',type:'taxonomy',method:{term:'recognition'},role:'识别特征',statement:'Feature.',content:{items:[{key:'available',title:'Available',meaning:'Available.'}],broader:[]}},{localKey:'classes',type:'taxonomy',method:{term:'recognition'},role:'类别定义',statement:'Classes.',content:{items:[],broader:[]}},{localKey:'match',type:'taxonomy',method:{term:'recognition'},role:'匹配办法',statement:'Mapping.',content:{items:[{key:'map',title:'Map',meaning:'Map.'}],broader:[]}}]};},'CREATION_METHOD_INCOMPLETE']];
for(const [label,mutate,code] of vocabularyNegatives)test('the method vocabulary law rejects '+label,()=>{const f=fixture();const a=clone(f.a);mutate(a);assert.throws(()=>f.s.agent.revise('signal',{baseRevision:1,alternatives:[a,f.b],explanation:'Vocabulary-negative mutation.'}),{code});});
test('two real semantic alternatives required',()=>{const f=fixture();assert.throws(()=>f.s.agent.revise('signal',{baseRevision:1,alternatives:[f.a],explanation:'One alternative.'}),{code:'CREATION_TWO_ALTERNATIVES_REQUIRED'});const b={...clone(f.a),localKey:'different-name',title:'Cosmetic only'};assert.throws(()=>f.s.agent.revise('signal',{baseRevision:1,alternatives:[f.a,b],explanation:'Names alone.'}),{code:'CREATION_ALTERNATIVES_NOT_DISTINCT'});});
test('preview invalidates on input revision and final cannot be reused',async()=>{const f=fixture();await f.select();f.s.agent.compilePreview();f.s.agent.revise('signal',{baseRevision:1,alternatives:[f.a,{...f.b,statement:'A revised alternate.'}],explanation:'New actual alternative.'});f.setReply('confirm');await assert.rejects(f.s.receiveAdoptionReply(),{code:'CREATION_FINAL_UNBOUND'});await f.select();await f.confirm();assert.throws(()=>f.s.agent.setBrief({title:'Change',scope:'After final'}),{code:'CREATION_SESSION_SEALED'});await assert.rejects(f.s.receiveAdoptionReply(),{code:'CREATION_SESSION_SEALED'});const out=f.s.exportAsset();assert.equal(f.s.completeSave(out.bytes).status,'accepted_with_live_context');assert.equal(api.verifyCreationEvidence(out.bytes,out.evidence,out.binding).status,'consistent');});
test('saved bytes re-signed as valid different asset cannot consume context',async()=>{const f=fixture({method:methods.recognition}),out=await f.ready();const plan=clone(buildMaterialization(out.evidence.context,descriptor,out.evidence.decision));plan.payload.judgments[0].result.value.value='Changed after final adoption.';const changed=encodeComponentRuntime(plan);assert.equal(core.admitBytes(changed).status,'accepted');assert.throws(()=>f.s.completeSave(changed),{code:'CREATION_SAVED_EXPECTATION_MISMATCH'});assert.throws(()=>f.s.completeSave(out.bytes),{code:'CREATION_SAVE_STATE_INVALID'});});
test('saved-readback invalid bytes burn one-shot completion',async()=>{const f=fixture(),out=await f.ready();assert.throws(()=>f.s.completeSave(Buffer.from('not an asset')),{code:'CREATION_SAVED_CORE_REJECTED'});assert.throws(()=>f.s.completeSave(out.bytes),{code:'CREATION_SAVE_STATE_INVALID'});});
test('external evidence binding rejects edited materials/history/final',async()=>{const f=fixture({method:methods.causalAnalysis}),out=await f.ready();for(const mutate of [e=>{e.context.materials[0].content+=' changed';},e=>{e.history[0].detail.scope+=' changed';},e=>{e.decision.actual_reply.response.text='Different adoption';},e=>{e.expected_component_bindings.reverse();}]){const e=clone(out.evidence);mutate(e);assert.equal(api.verifyCreationEvidence(out.bytes,e,out.binding).status,'inconsistent');}});
test('rehashing top binding cannot hide audit material mismatch',async()=>{const f=fixture(),out=await f.ready();const e=clone(out.evidence);e.context.materials[0].content+=' altered';e.decision.context_digest=whitebox.hash(e.context);const binding={...out.binding,evidence_digest:whitebox.hash(e)};const v=api.verifyCreationEvidence(out.bytes,e,binding);assert.equal(v.status,'inconsistent');assert.equal(v.reason,'CREATION_MATERIAL_MISMATCH');});
test('old evidence and fake authority do not obtain current acceptance',async()=>{const f=fixture(),out=await f.ready();for(const format of [undefined,{id:'kdna.studio-creation-evidence/1',version:'1.0.0'}]){const e=clone(out.evidence);if(format)e.format=format;else delete e.format;assert.equal(api.verifyCreationEvidence(out.bytes,e,out.binding).reason,'STUDIO_EVIDENCE_FORMAT_NOT_CURRENT');}const e=clone(out.evidence);e.creation_accepted='accepted';assert.equal(api.verifyCreationEvidence(out.bytes,e,{...out.binding,evidence_digest:whitebox.hash(e)}).reason,'CREATION_AUTHORITY_CLAIM_INVALID');});
test('busy callback rejects changes; abort cannot resume confirmation',async()=>{let release;const wait=new Promise(r=>release=r);let seenReview;const f=fixture({receive:async review=>{seenReview=review;await wait;return {id:'deferred',role:'agent',channel:f.options.adoptionInput.channel,review_id:review.review_id,text:'select'};}});const pending=f.s.receiveAdoptionReply();assert.throws(()=>f.s.agent.compilePreview(),{code:'CREATION_SESSION_BUSY'});f.s.abort();release();await assert.rejects(pending,{code:'CREATION_SESSION_ABORTED'});assert.throws(()=>f.s.exportAsset(),{code:'CREATION_FINAL_REQUIRED'});});
test('captured callback cannot be replaced through caller options',async()=>{const f=fixture();f.options.adoptionInput.receive=()=>{throw Error('Captured callback must not change');};await f.select();assert.equal(f.s.inspect().phase,'draft');});
test('actual repeated synthetic reply id is rejected',async()=>{let f;f=fixture({receive:async review=>({id:'same-reply',role:'agent',channel:f.options.adoptionInput.channel,review_id:review.review_id,text:review.preview?'confirm':'select'})});await f.select();f.s.agent.compilePreview();await assert.rejects(f.s.receiveAdoptionReply(),{code:'CREATION_REPLY_REPLAY'});assert.throws(()=>f.s.exportAsset(),{code:'CREATION_FINAL_REQUIRED'});});
test('cycle accepted as typed input is rejected by sole Core before Compiler',async()=>{const method=clone(methods.recognition);method.components[0].content.broader=[{narrowerKey:'available',broaderKey:'missing'},{narrowerKey:'missing',broaderKey:'available'}];const f=fixture({method});await f.select();await f.confirm();assert.throws(()=>f.s.exportAsset(),{code:'CREATION_EXPECTED_CORE_REJECTED'});});

test('explicit formation conditions remain empty without inventing result',async()=>{const f=fixture({method:methods.causalAnalysis});const a={...f.a,formationRule:{conditions:[]}},b={...f.b,formationRule:{conditions:[]}};f.s.agent.revise('signal',{baseRevision:1,alternatives:[a,b],explanation:'Explicitly retain the absence of overall prerequisites; candidate criteria remain separate.'});const out=await f.ready();const snapshot=core.admitBytes(out.bytes).snapshot;const judgment=snapshot.ir.nodes.find(n=>n.role==='judgment').value;assert.deepEqual(judgment.formation_rule.condition_refs,[]);assert.equal(Object.hasOwn(judgment,'result'),false);assert.equal(judgment.formation_rule.statement,a.statement);assert.equal(f.s.completeSave(out.bytes).status,'accepted_with_live_context');assert.equal(api.verifyCreationEvidence(out.bytes,out.evidence,out.binding).status,'consistent');});
